# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P3/P3.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P3/P3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P3/P3.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P3/P3.srcs/sources_1/new/P1.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P3/P3.srcs/constrs_1/imports/cenas/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P3/P3.srcs/constrs_1/imports/cenas/Nexys4_Master.xdc}}]


synth_design -top FSM_count_ones -part xc7a100tcsg324-1


write_checkpoint -force -noxdef FSM_count_ones.dcp

catch { report_utilization -file FSM_count_ones_utilization_synth.rpt -pb FSM_count_ones_utilization_synth.pb }
