# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{c:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/coe_from_java_ex2.coe}}
add_files -quiet {{C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}]
read_vhdl -library xil_defaultlib {
  {C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/sources_1/imports/Binario_BCD/SegmentDecoder.vhd}
  {C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/sources_1/new/max_min.vhd}
  {C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/sources_1/imports/Binario_BCD/DidplayControl.vhd}
  {C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/sources_1/new/ex57.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/constrs_1/imports/Nexys-4 XDC/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Asus/Documents/Universidade/4 Ano/CR/Aula4/Ex2/Ex2.srcs/constrs_1/imports/Nexys-4 XDC/Nexys4_Master.xdc}}]


synth_design -top Ex2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Ex2.dcp

catch { report_utilization -file Ex2_utilization_synth.rpt -pb Ex2_utilization_synth.pb }
