# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.srcs/sources_1/new/decoder.vhd}
  {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.srcs/sources_1/new/bintobcd.vhd}
  {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.srcs/sources_1/new/disp.vhd}
  {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.srcs/sources_1/new/clock_divider.vhd}
  {C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.srcs/sources_1/new/Ex4.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.srcs/constrs_1/imports/cenas/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Pedro Coelho/OneDrive/UA/4ano/CR/cr/P4/Ex4/Ex4.srcs/constrs_1/imports/cenas/Nexys4_Master.xdc}}]


synth_design -top TopTrivial -part xc7a100tcsg324-1


write_checkpoint -force -noxdef TopTrivial.dcp

catch { report_utilization -file TopTrivial_utilization_synth.rpt -pb TopTrivial_utilization_synth.pb }
